site_name: PyJDB
site_description: Advanced ORM for creating databases using JSON written in Python.

theme:
  name: material
  palette:
  - scheme: default
    primary: deep purple
    accent: amber
    toggle:
      icon: material/lightbulb
      name: Switch to dark mode
  - scheme: slate
    primary: deep purple
    accent: amber
    toggle:
      icon: material/lightbulb-outline
      name: Switch to light mode
  features:
  - search.suggest
  - search.highlight
  - content.tabs.link
  icon:
    repo: fontawesome/brands/github-alt
  language: en

repo_name: IHosseini083/PyJDB
repo_url: https://github.com/IHosseini083/PyJDB
edit_uri: ""

nav:
  - Overview: "index.md"

markdown_extensions:
  - toc:
      permalink: true
  - markdown.extensions.codehilite:
      guess_lang: false
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/IHosseini083/PyJDB
